# Generated by Django 4.2.13 on 2024-05-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='N/A', max_length=255),
        ),
    ]
