# Generated by Django 4.2.13 on 2024-05-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repassword',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
