# Generated by Django 4.2.13 on 2024-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_user_confirmed_alter_user_email_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activateUUID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
