# Generated by Django 5.0.6 on 2024-07-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_savedtickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='savedTickets',
            new_name='savedTicket',
        ),
    ]
