# Generated by Django 5.0.6 on 2024-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_savedtickets_savedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedticket',
            name='ticket',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
