# Generated by Django 5.0.6 on 2024-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_rename_ticket_savedticket_onefirstflightarrivalairport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedticket',
            name='zeroSecondFlightDepartureDate',
            field=models.CharField(default='', max_length=1000000000),
        ),
    ]
