# Generated by Django 5.0.6 on 2024-07-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_savedticket_zerosecondflightdeparturedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedticket',
            name='destination',
            field=models.CharField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='savedticket',
            name='origin',
            field=models.CharField(default='', max_length=1000000000),
        ),
    ]
