# Generated by Django 5.0.6 on 2024-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_savedticket_destination_savedticket_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedticket',
            name='departureDate',
            field=models.CharField(default='', max_length=1000000000),
        ),
        migrations.AddField(
            model_name='savedticket',
            name='returnDate',
            field=models.CharField(default='', max_length=1000000000),
        ),
    ]
