# Generated by Django 5.0.6 on 2024-07-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_savedticket_departuredate_savedticket_returndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidebarStatus',
            field=models.IntegerField(default=1),
        ),
    ]
