# Generated by Django 5.0.6 on 2024-07-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_user_sidebarstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sidebarStatus',
            field=models.IntegerField(default=0),
        ),
    ]
