# Generated by Django 5.0.6 on 2024-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_user_sidebarstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(default='', max_length=100)),
                ('departureDate', models.DateField()),
                ('returnDate', models.DateField()),
            ],
        ),
    ]
