# Generated by Django 5.0.6 on 2024-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='uid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
