# Generated by Django 5.0.6 on 2024-08-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_recentsearch_departuredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='creationDtTm',
            field=models.CharField(default='', max_length=100),
        ),
    ]
