# Generated by Django 5.0.6 on 2024-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_recentsearch_creationdttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedticket',
            name='destinationLocation',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='savedticket',
            name='originLocation',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
