# Generated by Django 5.0.6 on 2024-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_savedticket_destinationlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayStatus',
            field=models.IntegerField(default=0),
        ),
    ]
