# Generated by Django 5.0.6 on 2024-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_user_displaystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sidebarStatus',
            field=models.IntegerField(default=1),
        ),
    ]
